test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: ankaadb
  username: ankaa
  password: <%= ENV['MYANKAA_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

statistic_development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: statisticdb
  username: statistic
  password: <%= ENV['STATISTIC_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: myankaa-storage.local
  port: 5432
  database: ankaadb
  username: ankaa
  password: <%= ENV['MYANKAA_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

statistic_production:
  adapter: postgresql
  host: statistic-db.local
  port: 5432
  database: statisticdb
  username: statistic
  password: <%= ENV['STATISTIC_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000